part of 'app_pages.dart';

abstract class Routes {
  Routes._();
  static const SPLASH = _Paths.SPLASH;
  static const HOME = _Paths.HOME;
  static const EXPENSES = _Paths.EXPENSES;
  static const ADD_EXPENSES = _Paths.ADD_EXPENSES;
  static const EDIT_EXPENSE = _Paths.EDIT_EXPENSE;
  static const VIEW_EXPENSE = _Paths.VIEW_EXPENSE;
  static const EMPLOYEE = _Paths.EMPLOYEE;
  static const VIEW_EMPLOYEE = _Paths.VIEW_EMPLOYEE;
  static const ADD_EMPLOYEE = _Paths.ADD_EMPLOYEE;
  static const EDIT_EMPLOYEE = _Paths.EDIT_EMPLOYEE;
  static const WAGES = _Paths.WAGES;
  static const ADD_WAGES = _Paths.ADD_WAGES;
  static const EDIT_WAGES = _Paths.EDIT_WAGES;
  static const VIEW_WAGES = _Paths.VIEW_WAGES;
  static const VIEW_ATTENDANCE = _Paths.VIEW_ATTENDANCE;
  static const CREATE_ATTENDANCE = _Paths.CREATE_ATTENDANCE;
  static const EDIT_ATTENDANCE = _Paths.EDIT_ATTENDANCE;
  static const ATTENDANCE = _Paths.ATTENDANCE;
  static const EMPLOYEE_DETAILS = _Paths.EMPLOYEE_DETAILS;
  static const CROPS = _Paths.CROPS;
  static const SETTINGS = _Paths.SETTINGS;
  static const ADD_CROPS = _Paths.ADD_CROPS;
  static const EDIT_CROPS = _Paths.EDIT_CROPS;
  static const VIEW_CROPS = _Paths.VIEW_CROPS;
  static const CROPS_VARIANTS = _Paths.CROPS_VARIANTS;
  static const ADD_CROPS_VARIANTS = _Paths.ADD_CROPS_VARIANTS;
  static const VIEW_CROPS_VARIANTS = _Paths.VIEW_CROPS_VARIANTS;
  static const EDIT_CROPS_VARIANTS = _Paths.EDIT_CROPS_VARIANTS;
  static const MERCHANT = _Paths.MERCHANT;
  static const ADD_MERCHANT = _Paths.ADD_MERCHANT;
  static const VIEW_MERCHANT = _Paths.VIEW_MERCHANT;
  static const EDIT_MERCHANT = _Paths.EDIT_MERCHANT;
  static const FARM_SEGMENT = _Paths.FARM_SEGMENT;
  static const ADD_FARM_SEGMENT = _Paths.ADD_FARM_SEGMENT;
  static const VIEW_FARM_SEGMENT = _Paths.VIEW_FARM_SEGMENT;
  static const EDIT_FARM_SEGMENT = _Paths.EDIT_FARM_SEGMENT;
  static const YIELD = _Paths.YIELD;
  static const ADD_YIELD = _Paths.ADD_YIELD;
  static const VIEW_YIELD = _Paths.VIEW_YIELD;
  static const EDIT_YIELD = _Paths.EDIT_YIELD;
  static const SALES = _Paths.SALES;
  static const ADD_SALES = _Paths.ADD_SALES;
  static const SALES_REVIEW = _Paths.SALES_REVIEW;
  static const VIEW_SALES = _Paths.VIEW_SALES;
  static const EDIT_SALES = _Paths.EDIT_SALES;
  static const DASHBOARD = _Paths.DASHBOARD;

}

abstract class _Paths {
  _Paths._();
  static const SPLASH = '/splash';
  static const HOME = '/home';
  static const EXPENSES = '/expenses';
  static const ADD_EXPENSES = '/add_expenses';
  static const EDIT_EXPENSE = '/edit_expenses';
  static const VIEW_EXPENSE = '/view_expenses';
  static const EMPLOYEE = '/employee';
  static const VIEW_EMPLOYEE = '/view_employee';
  static const ADD_EMPLOYEE = '/add_employee';
  static const EDIT_EMPLOYEE = '/edit_employee';
  static const WAGES = '/wages';
  static const ADD_WAGES = '/add_wages';
  static const EDIT_WAGES = '/edit_wages';
  static const VIEW_WAGES = '/view_wages';
  static const VIEW_ATTENDANCE = '/view_attendance';
  static const CREATE_ATTENDANCE = '/create_attendance';
  static const EDIT_ATTENDANCE = '/edit_attendance';
  static const ATTENDANCE = '/attendance';
  static const EMPLOYEE_DETAILS = '/employee_details';
  static const CROPS = '/crops';
  static const ADD_CROPS = '/add_crops';
  static const SETTINGS = '/settings';
  static const EDIT_CROPS = '/edit_crops';
  static const VIEW_CROPS = '/view_crops';
  static const CROPS_VARIANTS = '/crop_variants';
  static const ADD_CROPS_VARIANTS = '/add_crop_variants';
  static const VIEW_CROPS_VARIANTS = '/view_crop_variants';
  static const EDIT_CROPS_VARIANTS = '/edit_crop_variants';
  static const MERCHANT = '/merchants';
  static const ADD_MERCHANT = '/add_merchant';
  static const VIEW_MERCHANT = '/view_merchant';
  static const EDIT_MERCHANT = '/edit_merchant';
  static const FARM_SEGMENT = '/farm_segments';
  static const ADD_FARM_SEGMENT = '/add_farm_segments';
  static const VIEW_FARM_SEGMENT = '/view_farm_segments';
  static const EDIT_FARM_SEGMENT = '/edit_farm_segments';
  static const YIELD = '/yield';
  static const ADD_YIELD = '/add_yield';
  static const VIEW_YIELD = '/view_yield';
  static const EDIT_YIELD = '/edit_yield';
  static const SALES = '/sales';
  static const ADD_SALES = '/add_sales';
  static const SALES_REVIEW = '/sales_review';
  static const VIEW_SALES = '/view_sales';
  static const EDIT_SALES = '/edit_sales';
  static const DASHBOARD = '/dashboard';
}
